# Generated by Django 3.2.16 on 2022-12-13 04:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221212_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
